import { PrismaClient } from "../generated/prisma";

const prisma = new PrismaClient();

async function main() {
  const companies = await prisma.company.createMany({
    data: [
      { name: "Team Cherry", industry: "Videojuegos" },
      { name: "Vercel", industry: "Tecnología" },
      { name: "Nintendo", industry: "Videojuegos" },
      { name: "Microsoft", industry: "Tecnología" },
      { name: "Santa Monica", industry: "Videojuegos" },
    ],
    skipDuplicates: true,
  });

  const allCompanies = await prisma.company.findMany();

  const usersData = [
    {
      email: "maria.rodriguez@tecnoinova.com",
      name: "María Rodríguez",
      country: "México",
      age: 29,
      gender: "Femenino",
      phone: "5551234567",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "carlos.fernandez@digitalsol.es",
      name: "Carlos Fernández",
      country: "España",
      age: 34,
      gender: "Masculino",
      phone: "918765432",
      companyId: allCompanies[1]?.id,
    },
    {
      email: "ana.martinez@innovatech.ar",
      name: "Ana Martínez",
      country: "Argentina",
      age: 27,
      gender: "Femenino",
      phone: "1145678901",
      companyId: allCompanies[2]?.id,
    },
    {
      email: "luis.garcia@globalcorp.co",
      name: "Luis García",
      country: "Colombia",
      age: 31,
      gender: "Masculino",
      phone: "12345678",
      companyId: allCompanies[3]?.id,
    },
    {
      email: "sofia.lopez@futurebiz.cl",
      name: "Sofía López",
      country: "Chile",
      age: 26,
      gender: "Femenino",
      phone: "29876543",
      companyId: allCompanies[4]?.id,
    },
    {
      email: "diego.morales@techventure.mx",
      name: "Diego Morales",
      country: "México",
      age: 38,
      gender: "Masculino",
      phone: "813456789",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "elena.vargas@innovaspa.es",
      name: "Elena Vargas",
      country: "España",
      age: 25,
      gender: "Femenino",
      phone: "934567890",
      companyId: allCompanies[1]?.id,
    },
    {
      email: "pablo.herrera@datasys.ar",
      name: "Pablo Herrera",
      country: "México",
      age: 42,
      gender: "Masculino",
      phone: "2617890123",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "camila.torres@smarttech.co",
      name: "Camila Torres",
      country: "Colombia",
      age: 30,
      gender: "Femenino",
      phone: "45678901",
      companyId: allCompanies[3]?.id,
    },
    {
      email: "andres.silva@nextgen.cl",
      name: "Andrés Silva",
      country: "Chile",
      age: 33,
      gender: "Masculino",
      phone: "326789012",
      companyId: allCompanies[4]?.id,
    },
    {
      email: "valeria.castro@digitalmx.com",
      name: "Valeria Castro",
      country: "México",
      age: 28,
      gender: "Femenino",
      phone: "338901234",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "javier.ruiz@techspa.es",
      name: "Javier Ruiz",
      country: "España",
      age: 36,
      gender: "Masculino",
      phone: "951234567",
      companyId: allCompanies[1]?.id,
    },
    {
      email: "laura.mendez@sysinno.ar",
      name: "Laura Méndez",
      country: "Argentina",
      age: 24,
      gender: "Femenino",
      phone: "3412345678",
      companyId: allCompanies[2]?.id,
    },
    {
      email: "ricardo.jimenez@procol.co",
      name: "Ricardo Jiménez",
      country: "Colombia",
      age: 39,
      gender: "Masculino",
      phone: "23456789",
      companyId: allCompanies[3]?.id,
    },
    {
      email: "daniela.reyes@innovacl.cl",
      name: "Daniela Reyes",
      country: "Chile",
      age: 32,
      gender: "Femenino",
      phone: "414567890",
      companyId: allCompanies[4]?.id,
    },
    {
      email: "miguel.ortega@techmx.net",
      name: "Miguel Ortega",
      country: "México",
      age: 41,
      gender: "Masculino",
      phone: "2225678901",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "isabella.romero@futurees.com",
      name: "Isabella Romero",
      country: "España",
      age: 23,
      gender: "Femenino",
      phone: "966789012",
      companyId: allCompanies[1]?.id,
    },
    {
      email: "fernando.aguilar@dataar.com",
      name: "Fernando Aguilar",
      country: "Argentina",
      age: 37,
      gender: "Masculino",
      phone: "2217890123",
      companyId: allCompanies[2]?.id,
    },
    {
      email: "natalia.guerrero@innovaco.co",
      name: "Natalia Guerrero",
      country: "Colombia",
      age: 29,
      gender: "Femenino",
      phone: "58901234",
      companyId: allCompanies[2]?.id,
    },
    {
      email: "sebastian.pena@smartcl.org",
      name: "Sebastián Peña",
      country: "Chile",
      age: 35,
      gender: "Masculino",
      phone: "519012345",
      companyId: allCompanies[4]?.id,
    },
    {
      email: "carla.santos@techbrasil.com.br",
      name: "Carla Santos",
      country: "Brasil",
      age: 31,
      gender: "Femenino",
      phone: "11987654321",
      companyId: allCompanies[2]?.id,
    },
    {
      email: "alberto.vega@innovamx.net",
      name: "Alberto Vega",
      country: "México",
      age: 28,
      gender: "Masculino",
      phone: "4449876543",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "lucia.paredes@globalpe.com",
      name: "Lucía Paredes",
      country: "Perú",
      age: 26,
      gender: "Femenino",
      phone: "987123456",
      companyId: allCompanies[2]?.id,
    },
    {
      email: "gonzalo.ramirez@futuretech.uy",
      name: "Gonzalo Ramírez",
      country: "Uruguay",
      age: 33,
      gender: "Masculino",
      phone: "99234567",
      companyId: allCompanies[1]?.id,
    },
    {
      email: "patricia.molina@digitales.es",
      name: "Patricia Molina",
      country: "España",
      age: 29,
      gender: "Femenino",
      phone: "678901234",
      companyId: allCompanies[3]?.id,
    },
    {
      email: "rafael.costa@innovabr.com",
      name: "Rafael Costa",
      country: "Brasil",
      age: 35,
      gender: "Masculino",
      phone: "21976543210",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "monica.flores@techcl.org",
      name: "Mónica Flores",
      country: "Chile",
      age: 24,
      gender: "Femenino",
      phone: "612345678",
      companyId: allCompanies[2]?.id,
    },
    {
      email: "eduardo.leon@smartco.co",
      name: "Eduardo León",
      country: "Colombia",
      age: 40,
      gender: "Masculino",
      phone: "34567890",
      companyId: allCompanies[1]?.id,
    },
    {
      email: "alejandra.campos@innovaar.com",
      name: "Alejandra Campos",
      country: "Argentina",
      age: 32,
      gender: "Femenino",
      phone: "1567890123",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "roberto.medina@digitalmx.com",
      name: "Roberto Medina",
      country: "México",
      age: 27,
      gender: "Masculino",
      phone: "5567891234",
      companyId: allCompanies[3]?.id,
    },
    {
      email: "beatriz.silva@techpe.net",
      name: "Beatriz Silva",
      country: "Perú",
      age: 30,
      gender: "Femenino",
      phone: "965432109",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "matias.gonzalez@futurebr.com",
      name: "Matías González",
      country: "Brasil",
      age: 34,
      gender: "Masculino",
      phone: "11945678901",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "carmen.delgado@smartes.org",
      name: "Carmen Delgado",
      country: "España",
      age: 25,
      gender: "Femenino",
      phone: "623456789",
      companyId: allCompanies[1]?.id,
    },
    {
      email: "francisco.torres@globaluy.net",
      name: "Francisco Torres",
      country: "Uruguay",
      age: 37,
      gender: "Masculino",
      phone: "96345678",
      companyId: allCompanies[4]?.id,
    },
    {
      email: "adriana.moreno@techco.com",
      name: "Adriana Moreno",
      country: "Colombia",
      age: 28,
      gender: "Femenino",
      phone: "67890123",
      companyId: allCompanies[3]?.id,
    },
    {
      email: "ignacio.rojas@innovacl.cl",
      name: "Ignacio Rojas",
      country: "Chile",
      age: 36,
      gender: "Masculino",
      phone: "787012345",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "valentina.ramos@digitalar.com",
      name: "Valentina Ramos",
      country: "Argentina",
      age: 23,
      gender: "Femenino",
      phone: "2634567890",
      companyId: allCompanies[0]?.id,
    },
    {
      email: "marco.herrera@futuremx.org",
      name: "Marco Herrera",
      country: "México",
      age: 41,
      gender: "Masculino",
      phone: "6678901234",
      companyId: allCompanies[2]?.id,
    },
    {
      email: "cristina.vargas@smartpe.net",
      name: "Cristina Vargas",
      country: "Perú",
      age: 29,
      gender: "Femenino",
      phone: "954321087",
      companyId: allCompanies[4]?.id,
    },
    {
      email: "gustavo.pereira@techbr.com",
      name: "Gustavo Pereira",
      country: "Brasil",
      age: 38,
      gender: "Masculino",
      phone: "85987654321",
      companyId: allCompanies[3]?.id,
    },
  ];

  await prisma.user.createMany({
    data: usersData,
    skipDuplicates: true,
  });

  console.log("¡Datos de prueba insertados!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
